# file      : cxx/serializer/validation/built-in/qname/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

if ($build.meta_operation != 'dist')
{
  assert ($serializer_validation) \
    "config.xsde_tests.serializer_validation should be set to true for this test"

  assert (!$custom_allocator || $default_allocator) \
    "config.xsde_tests.default_allocator should be set to true for this test"
}

import libs = libxsde%liba{xsde}

exe{driver}: {hxx cxx}{*} $libs
