# file      : cxx/serializer/hello/buildfile
# license   : not copyrighted - public domain

if ($build.meta_operation != 'dist')
{
  assert ($stl) \
    "config.xsde_examples.stl should be set to true for this example"

  assert ($iostream) \
    "config.xsde_examples.iostream should be set to true for this example"

  assert ($exceptions) \
    "config.xsde_examples.exceptions should be set to true for this example"

  assert (!$custom_allocator || $default_allocator) \
    "config.xsde_examples.default_allocator should be set to true for this example"
}

import libs = libxsde%liba{xsde}

./: exe{driver} doc{README}

exe{driver}: {hxx cxx}{* -hello-sskel} {hxx ixx cxx}{hello-sskel} $libs

<{hxx ixx cxx}{hello-sskel}>: xsd{hello} $xsde
{{
  # For options contained in cxx_serializer_options variable see
  # build/root.build.
  #
  $xsde cxx-serializer $cxx_serializer_options \
        --output-dir $out_base                 \
        $path($<[0])
}}

cxx.poptions =+ "-I$out_base"
