# file      : cxx/hybrid/binary/xdr/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

if ($build.meta_operation != 'dist')
{
  assert ($xdr) \
    "config.xsde_tests.xdr should be set to true for this test"

  assert ($iostream) \
    "config.xsde_tests.iostream should be set to true for this test"

  assert ($parser_validation) \
    "config.xsde_tests.parser_validation should be set to true for this test"

  assert ($reuse_style != 'none') \
    "config.xsde_tests.reuse_style should not be set to 'none' for this test"

  assert (!$custom_allocator || $default_allocator) \
    "config.xsde_tests.default_allocator should be set to true for this test"
}

import libs = libxsde%lib{xsde}

if ($cxx.target.class == 'linux')
  import libs += libtirpc%lib{tirpc}

exe{driver}: {hxx     cxx}{* -test -test-pskel -test-pimpl  \
                                   -test-sskel -test-simpl} \
             {hxx ixx cxx}{   test  test-pskel  test-sskel} \
             {hxx     cxx}{         test-pimpl  test-simpl} \
             $libs

exe{driver}: xml{test-000}: test.input  = true
exe{driver}: std{test-000}: test.stdout = true

<{hxx ixx cxx}{test test-pskel test-sskel}                   \
 {hxx     cxx}{     test-pimpl test-simpl}>: xsd{test} $xsde
{{
  $xsde cxx-hybrid $cxx_hybrid_options \
        --generate-parser              \
        --generate-serializer          \
        --generate-aggregate           \
        --generate-extraction XDR      \
        --generate-insertion XDR       \
        --output-dir $out_base         \
        $path($<[0])
}}

cxx.poptions =+ "-I$out_base"

if ($reuse_style == 'mixin' && $cxx.class == 'gcc')
  cxx.coptions += -Wno-overloaded-virtual
