# file      : cxx/hybrid/allocator/buildfile
# license   : not copyrighted - public domain

if ($build.meta_operation != 'dist')
{
  assert ($custom_allocator) \
    "config.xsde_examples.custom_allocator should be set to true for this example"

  assert (!$default_allocator) \
    "config.xsde_examples.default_allocator should be set to false for this example"

  assert (!$stl) \
    "config.xsde_examples.stl should be set to false for this example"

  assert (!$iostream) \
    "config.xsde_examples.iostream should be set to false for this example"

  assert (!$exceptions) \
    "config.xsde_examples.exceptions should be set to false for this example"
}

import libs = libxsde%liba{xsde}

./: exe{driver} doc{README}

exe{driver}: {hxx     cxx}{* -people -people-pskel -people-pimpl  \
                                     -people-sskel -people-simpl} \
             {hxx ixx cxx}{   people  people-pskel  people-sskel} \
             {hxx     cxx}{           people-pimpl  people-simpl} \
             $libs

exe{driver}: xml{people}: test.input = true

<{hxx ixx cxx}{people people-pskel people-sskel}                     \
 {hxx     cxx}{       people-pimpl people-simpl}>: xsd{people} $xsde
{{
  # For options contained in cxx_hybrid_options variable see build/root.build.
  #
  $xsde cxx-hybrid $cxx_hybrid_options \
        --generate-parser              \
        --generate-serializer          \
        --generate-aggregate           \
        --output-dir $out_base         \
        $path($<[0])
}}

cxx.poptions =+ "-I$out_base" "-I$src_base"
