# file      : cxx/hybrid/reorder/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

if ($build.meta_operation != 'dist')
{
  assert ($reuse_style != 'none') \
    "config.xsde_tests.reuse_style should not be set to 'none' for this test"

  assert (!$custom_allocator || $default_allocator) \
    "config.xsde_tests.default_allocator should be set to true for this test"
}

import libs = libxsde%lib{xsde}

exe{driver}: {hxx     cxx}{* -test -test-pskel -test-pimpl  \
                                   -test-sskel -test-simpl} \
             {hxx ixx cxx}{   test  test-pskel  test-sskel} \
             {hxx     cxx}{         test-pimpl  test-simpl} \
             $libs

<{hxx ixx cxx}{test test-pskel test-sskel}                   \
 {hxx     cxx}{     test-pimpl test-simpl}>: xsd{test} $xsde
{{
  $xsde cxx-hybrid $cxx_hybrid_options \
        --generate-parser              \
        --generate-serializer          \
        --generate-aggregate           \
        --output-dir $out_base         \
        $path($<[0])
}}

cxx.poptions =+ "-I$out_base"

if ($reuse_style == 'mixin' && $cxx.class == 'gcc')
  cxx.coptions += -Wno-overloaded-virtual
