# file      : cxx/serializer/choice/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

if ($build.meta_operation != 'dist')
{
  assert ($iostream) \
    "config.xsde_tests.iostream should be set to true for this test"

  assert (!$custom_allocator || $default_allocator) \
    "config.xsde_tests.default_allocator should be set to true for this test"
}

import libs = libxsde%lib{xsde}

exe{driver}: {hxx cxx}{* -test-sskel} {hxx ixx cxx}{test-sskel} $libs

exe{driver}: std{test-000}: test.stdout = true

<{hxx ixx cxx}{test-sskel}>: xsd{test} $xsde
{{
  $xsde cxx-serializer $cxx_serializer_options \
        --output-dir $out_base                 \
        $path($<[0])
}}

cxx.poptions =+ "-I$out_base"
